project:
  type: website

website:
  title: "Brad Cannell's Wiki"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: sops/task_management/task_management.qmd
        text: Task Management

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



